// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(robot) {
    return robot.hear(/@hubot Hello/i, function(msg) {
      var username;
      username = msg.message.user.name;
      return msg.send("Hello, " + username);
    });
  };

}).call(this);

//# sourceMappingURL=slack-hello.js.map
